baseURL = "krieg.github.io"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hyde-hyde"


[params.social]
	twitter = "htr3n"
	facebook = "htr3n"
	github = "htr3n"
  linkedin = "htr3n"
  stackOverflow = "htr3n"

[[menu.main]]
    name = "Posts"
    identifier = "post"
    weight = 1
    url = "/posts/"


[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 2
    url = "/portfolio/"

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 3

    url = "/about/"
